name: Create Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: dev
          title: 'Merge dev into main'
          body: 'Automatically created pull request from dev to main.'

          # You can customize these options if needed
          labels: 'automated-pr'
          reviewers: 'username1,username2'
          assignees: 'username3'
