name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push client Docker image
      working-directory: client
      run: |
        docker build -t your-dockerhub-username/client-image:latest .
        docker push your-dockerhub-username/client-image:latest

    - name: Build and push server Docker image
      working-directory: server
      run: |
        docker build -t your-dockerhub-username/server-image:latest .
        docker push your-dockerhub-username/server-image:latest
